// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

import (
	"github.com/gofiber/fiber/v2"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Очистка всех данных в базе
	// (POST /service/clear)
	Clear(c *fiber.Ctx) error
	// Получение инфомарции о базе данных
	// (GET /service/status)
	Status(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// Clear operation middleware
func (siw *ServerInterfaceWrapper) Clear(c *fiber.Ctx) error {

	return siw.Handler.Clear(c)
}

// Status operation middleware
func (siw *ServerInterfaceWrapper) Status(c *fiber.Ctx) error {

	return siw.Handler.Status(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Post(options.BaseURL+"/service/clear", wrapper.Clear)

	router.Get(options.BaseURL+"/service/status", wrapper.Status)

}
